# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('tel_number', models.CharField(max_length=100, verbose_name='Контактный телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='Контактный e-mail')),
                ('add_info', models.CharField(max_length=200, verbose_name='доп. информация')),
                ('beard_model', models.CharField(choices=[('0', 'адмирал'), ('1', 'лесоруб'), ('2', 'полярник'), ('3', 'боярин'), ('4', 'мудрец')], max_length=100, verbose_name='модель бороды')),
                ('is_beard_paint', models.BooleanField(default=False, verbose_name='Подкрасить бороду')),
                ('is_beard_brush', models.BooleanField(default=False, verbose_name='Причесать бороду')),
                ('is_remove_gray', models.BooleanField(default=False, verbose_name='Убрать седину')),
                ('is_moustache_spin', models.BooleanField(default=False, verbose_name='Накрутить усы')),
                ('is_trim', models.BooleanField(default=False, verbose_name='Подровнять виски')),
                ('is_polish_head', models.BooleanField(default=False, verbose_name='отполировать лысину')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('date_record', models.DateTimeField(verbose_name='дата и время записи')),
            ],
            options={
                'verbose_name': 'запись на прием',
                'verbose_name_plural': 'записи на прием',
                'ordering': ['-date_record'],
            },
        ),
    ]
