# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0004_auto_20171219_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='add_info',
            field=models.TextField(max_length=200, verbose_name='доп. информация'),
        ),
    ]
