# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('is_haircut', models.BooleanField(default=False)),
                ('is_shave', models.BooleanField(default=False)),
                ('is_moustache', models.BooleanField(default=False)),
                ('is_best_month_job', models.BooleanField(default=False)),
            ],
        ),
    ]
