# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='review',
            name='is_best_month_job',
            field=models.BooleanField(default=False, verbose_name='работа месяца'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_haircut',
            field=models.BooleanField(default=False, verbose_name='стрижка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_moustache',
            field=models.BooleanField(default=False, verbose_name='усы'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_shave',
            field=models.BooleanField(default=False, verbose_name='бритье'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='image',
            field=models.ImageField(upload_to='reviews', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='главное фото'),
        ),
    ]
