# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20171204_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['date_created'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
