# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='version',
            field=models.BooleanField(default=False, verbose_name='Отображать на сайте'),
        ),
    ]
