# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price_list', '0002_pricelist_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайсы'},
        ),
    ]
